# Generated by Django 3.1.5 on 2021-01-24 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20210123_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likepost',
        ),
        migrations.RemoveField(
            model_name='like',
            name='likeuser',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=datetime.datetime(2021, 1, 24, 15, 15, 48, 541822, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
