# Generated by Django 3.1.5 on 2021-01-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210124_1150'),
        ('blog', '0005_auto_20210124_1016'),
    ]

    operations = [
    ]
